statement: "QUERY" return "WHERE" condition+

return: "MS1DATA"
     | "MS2DATA"
     | function"(MS1DATA)"
     | function"(MS2DATA)"

condition: filterfields "=" NUMBER
    | filterfields "=" STRING
    | "OR" filterfields "=" NUMBER
    | "AND" filterfields "=" NUMBER

filterfields: "MS2PROD"
    | "MS2PREC"

function: "scanrangesum"
    | "scansum"

%import common.ESCAPED_STRING   -> STRING
%import common.SIGNED_NUMBER    -> NUMBER
%import common.WS
%ignore WS