-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=fast_test_workflow
TOOL_FOLDER_NAME=fast_test_workflow
WORKFLOW_VERSION=release_2
WORKFLOW_DESCRIPTION="Example Fast Run Workflow, this description is optional"