-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=msql-nf
TOOL_FOLDER_NAME=msql-nf
WORKFLOW_VERSION=release_29.6
WORKFLOW_DESCRIPTION="MSQL NF - <a href='https://mwang87.github.io/MassQueryLanguage_Documentation/'>Documentation Link</a>"