-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=msql-nf
TOOL_FOLDER_NAME=msql-nf
WORKFLOW_VERSION=release_29.16
WORKFLOW_DESCRIPTION="MassQL Query Workflow - <a href='https://mwang87.github.io/MassQueryLanguage_Documentation/'>Documentation Link</a>. Currently Supports v1.0 of MassQL" 