-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=msql-repo-nf
TOOL_FOLDER_NAME=msql-repo-nf
WORKFLOW_VERSION=release_29.6
WORKFLOW_DESCRIPTION="MSQL Repository Scale NF"