-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=msql-repo-full-nf
TOOL_FOLDER_NAME=msql-repo-full-nf
WORKFLOW_VERSION=release_31.1
WORKFLOW_DESCRIPTION="<img src="https://mwang87.github.io/MassQueryLanguage_Documentation/img/logo.png" width="400"><br>\
MassQL Repository Scale NF. Currently Supports v1.0 of MassQL"