-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=msql-repo-full-nf
TOOL_FOLDER_NAME=msql-repo-full-nf
WORKFLOW_VERSION=release_29.13
WORKFLOW_DESCRIPTION="MSQL Repository Scale NF. Currently Supports v1.0 of MassQL"