//! End-to-end engine parity vs. the Python `msql_engine`. For each
//! `(mzml, query)` pair we (a) load the file in Rust, (b) run the
//! query, and (c) compare the output row set against a JSON reference
//! generated by running the Python engine on the same inputs.
//!
//! The reference is keyed on the sorted set of `scan` column values
//! and a hash of the full row payload — that's precise enough to catch
//! wrong aggregations without depending on pandas' column-order or
//! float formatting.

use std::collections::BTreeSet;
use std::path::PathBuf;

use massql_engine::process_query;
use massql_loader::load_mzml;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf()
}

#[derive(serde::Deserialize)]
struct Reference {
    row_count: usize,
    scans: Vec<u32>,
    /// Scan-indexed digest of aggregated fields. Only present for
    /// scaninfo queries where we can compare per-scan aggregates.
    #[serde(default)]
    per_scan: Vec<PerScan>,
}

#[derive(serde::Deserialize)]
struct PerScan {
    scan: u32,
    rt: f64,
    i_sum: f64,
    i_norm_max: f64,
    /// For MS2 scaninfo.
    #[serde(default)]
    precmz: Option<f64>,
    #[serde(default)]
    ms1scan: Option<u32>,
    #[serde(default)]
    charge: Option<i32>,
    /// Variable-pipeline rows — multiple per scan, one per X
    /// candidate. Used to key the lookup so rows for the same scan
    /// but different X don't collide.
    #[serde(default)]
    comment: Option<f64>,
}

fn run(mzml_rel: &str, query: &str, reference_name: &str) {
    let root = repo_root();
    let mzml = root.join(mzml_rel);
    let reference_path = root
        .join("rust/references/engine")
        .join(format!("{}.json", reference_name));

    if !reference_path.exists() {
        panic!(
            "missing reference {} — generate with rust/references/dump_engine_reference.py",
            reference_path.display()
        );
    }
    let reference: Reference =
        serde_json::from_str(&std::fs::read_to_string(&reference_path).unwrap()).unwrap();

    let dataset = load_mzml(&mzml).expect("load_mzml");
    let result = process_query(query, &dataset).expect("process_query");

    let scans: BTreeSet<u32> = result
        .rows
        .iter()
        .filter_map(|r| r.scan)
        .collect();
    let ref_scans: BTreeSet<u32> = reference.scans.iter().copied().collect();

    assert_eq!(
        result.rows.len(),
        reference.row_count,
        "row count mismatch — Rust={}, Python={}, file={}, query={}",
        result.rows.len(),
        reference.row_count,
        mzml_rel,
        query,
    );
    assert_eq!(
        scans, ref_scans,
        "scan set mismatch\nquery: {}\nfile: {}",
        query, mzml_rel,
    );

    // Per-scan aggregate comparison for scaninfo queries. When the
    // result set comes from the variable pipeline there can be many
    // rows per scan (one per X candidate), so we key on (scan, trunc(X))
    // to dedupe — the same key Python uses for de-dup on its side.
    if !reference.per_scan.is_empty() {
        let by_key: std::collections::HashMap<(u32, i64), &_> = result
            .rows
            .iter()
            .map(|r| {
                let key = r.comment.map(|c| c.trunc() as i64).unwrap_or(0);
                ((r.scan.unwrap(), key), r)
            })
            .collect();

        for ps in &reference.per_scan {
            let key = ps.comment.map(|c| c.trunc() as i64).unwrap_or(0);
            let row = by_key
                .get(&(ps.scan, key))
                .unwrap_or_else(|| panic!("Rust missing (scan={}, X={:?}) for query {}", ps.scan, ps.comment, query));
            assert!(
                approx_eq(row.rt.unwrap(), ps.rt, 1e-5),
                "rt mismatch scan={} got={} exp={}",
                ps.scan,
                row.rt.unwrap(),
                ps.rt
            );
            assert!(
                approx_eq(row.i.unwrap(), ps.i_sum, 1e-2_f64.max(ps.i_sum.abs() * 1e-5)),
                "i_sum mismatch scan={} got={} exp={}",
                ps.scan,
                row.i.unwrap(),
                ps.i_sum
            );
            assert!(
                approx_eq(row.i_norm.unwrap(), ps.i_norm_max, 1e-5),
                "i_norm_max mismatch scan={} got={} exp={}",
                ps.scan,
                row.i_norm.unwrap(),
                ps.i_norm_max
            );
            if let Some(exp) = ps.precmz {
                assert!(
                    approx_eq(row.precmz.unwrap(), exp, 1e-5),
                    "precmz mismatch scan={}",
                    ps.scan
                );
            }
            if let Some(exp) = ps.ms1scan {
                assert_eq!(row.ms1scan.unwrap(), exp, "ms1scan mismatch scan={}", ps.scan);
            }
            if let Some(exp) = ps.charge {
                assert_eq!(row.charge.unwrap(), exp, "charge mismatch scan={}", ps.scan);
            }
        }
    }
}

fn approx_eq(a: f64, b: f64, tol: f64) -> bool {
    (a - b).abs() <= tol
}

#[test]
fn scaninfo_ms2_simple_mz_tolerance() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE MS2PROD=226.18:TOLERANCEMZ=0.1",
        "a3p_ms2prod_226",
    );
}

#[test]
fn scaninfo_ms2_ppm_tolerance() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE MS2PROD=226.18:TOLERANCEPPM=5",
        "a3p_ms2prod_226_ppm",
    );
}

#[test]
fn scaninfo_ms1_polarity() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS1DATA) WHERE POLARITY=Positive",
        "a3p_polarity_positive",
    );
}

#[test]
fn scaninfo_ms2_two_conditions_and() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE MS2PROD=86.09643:TOLERANCEMZ=0.01 AND MS2PROD=104.1075:TOLERANCEMZ=0.01",
        "a3p_ms2prod_and",
    );
}

#[test]
fn scaninfo_ms2_neutral_loss() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE MS2NL=18.0:TOLERANCEMZ=0.05",
        "a3p_ms2nl_18",
    );
}

#[test]
fn scansum_ms1() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scansum(MS1DATA) WHERE MS1MZ=100:TOLERANCEMZ=0.1",
        "a3p_scansum_ms1_100",
    );
}

#[test]
fn scannum_ms2() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scannum(MS2DATA) WHERE MS2PREC=226.18:TOLERANCEMZ=0.5",
        "a3p_scannum_prec226",
    );
}

#[test]
fn polarity_negative() {
    run(
        "tests/data/GNPS00002_A10_n.mzML",
        "QUERY scaninfo(MS1DATA) WHERE POLARITY=Negative",
        "a10n_polarity_negative",
    );
}

#[test]
fn scan_range() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS1DATA) WHERE SCANMIN=20 AND SCANMAX=30",
        "a3p_scan_range",
    );
}

#[test]
fn rt_range() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS1DATA) WHERE RTMIN=0.1 AND RTMAX=0.2",
        "a3p_rt_range",
    );
}

#[test]
fn charge_filter() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE CHARGE=1",
        "a3p_charge1",
    );
}

#[test]
fn intensity_percent() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE MS2PROD=86.09643:TOLERANCEMZ=0.01:INTENSITYPERCENT>10",
        "a3p_intensity_percent",
    );
}

#[test]
fn intensity_tic_percent() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE MS2PROD=86.09643:TOLERANCEMZ=0.01:INTENSITYTICPERCENT>5",
        "a3p_intensity_tic_percent",
    );
}

#[test]
fn intensity_value() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE MS2PROD=86.09643:TOLERANCEMZ=0.01:INTENSITYVALUE>500",
        "a3p_intensity_value",
    );
}

#[test]
fn excluded() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE MS2PROD=226.18:TOLERANCEPPM=5:EXCLUDED",
        "a3p_excluded",
    );
}

#[test]
fn formula_c10() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE MS2PROD=formula(C10)",
        "a3p_formula_c10",
    );
}

#[test]
fn filter_clause_ms1() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scansum(MS1DATA) WHERE MS1MZ=100:TOLERANCEMZ=0.5 FILTER MS1MZ=100:TOLERANCEMZ=0.1",
        "a3p_filter_ms1",
    );
}

#[test]
fn or_list() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE MS2PROD=(86.09643 OR 104.1075):TOLERANCEMZ=0.01",
        "a3p_or_list",
    );
}

#[test]
fn massdefect_qualifier() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE MS2PROD=100:TOLERANCEMZ=100:MASSDEFECT=massdefect(min=0.05, max=0.15)",
        "a3p_massdefect",
    );
}

#[test]
fn filter_with_massdefect() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scansum(MS1DATA) FILTER MS1MZ=515:TOLERANCEMZ=35:MASSDEFECT=massdefect(min=0.1332, max=0.2112)",
        "a3p_filter_massdefect",
    );
}

#[test]
fn variable_prod_minus_formula() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE MS2PROD=X AND MS2PROD=2.0*(X - formula(Fe))",
        "a3p_var_prod_fe",
    );
}

#[test]
fn variable_prod_offset() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE MS2PROD=X :TOLERANCEMZ=0.1:INTENSITYPERCENT=5 AND MS2PROD=X+119.1 :TOLERANCEMZ=0.1:INTENSITYPERCENT=5",
        "a3p_var_prod_119",
    );
}

#[test]
fn variable_ms1_or_list() {
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS1DATA) WHERE MS1MZ=(X OR X+2 OR X+4 OR X+6)",
        "a3p_var_ms1_or",
    );
}

#[test]
fn intensitymatch_iron_isotope() {
    run(
        "tests/data/JB_182_2_fe.mzML",
        "QUERY scaninfo(MS1DATA) WHERE RTMIN=3.03 AND RTMAX=3.05 AND MS1MZ=X-2:INTENSITYMATCH=Y*0.063:INTENSITYMATCHPERCENT=25 AND MS1MZ=X:INTENSITYMATCH=Y:INTENSITYMATCHREFERENCE FILTER MS1MZ=X",
        "jb_iron_isotope",
    );
}

#[test]
fn intensitymatch_yfx_expression() {
    // Y*f(X) inside the match qualifier — exercises the full path:
    // per-candidate X substitution into the match expression, then
    // Y-register read per scan. Expected 0 rows; regression check
    // that we don't over-accept the way Rust did before the pre-filter
    // narrowed the candidate pool.
    run(
        "tests/data/GNPS00002_A3_p.mzML",
        "QUERY scaninfo(MS2DATA) WHERE MS1MZ=X-2:INTENSITYMATCH=Y*(0.0608+(.000002*X)):INTENSITYMATCHPERCENT=25 AND MS1MZ=X:INTENSITYMATCH=Y:INTENSITYMATCHREFERENCE:INTENSITYPERCENT=5 AND MS2PREC=X",
        "a3p_intensitymatch_yfx",
    );
}
